version: "3"
services:
  database:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-for-hourly
    ports:
      - "5432:5432" # HOST_PORT:CONTAINER_PORT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_RUN_MODE=$VITE_RUN_MODE
        - VITE_LOC_BASE_URL=$VITE_LOC_BASE_URL
        - VITE_DEV_BASE_URL=$VITE_DEV_BASE_URL
        - VITE_PROD_BASE_URL=$VITE_PROD_BASE_URL
        - VITE_ROSTER_SSO_JHU_URL=$VITE_ROSTER_SSO_JHU_URL
    ports:
      - "3000:80"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=$DATABASE_URL
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=$DATABASE_URL
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - client
      - server
