version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    ports:
      - ${DB_PORT}:5432 # HOST_PORT:CONTAINER_PORT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres-for-hourly
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
      # spam in the logs
      test: ["CMD", "pg_isready", "-U", "prisma", "-d", "postgres-for-hourly"]
      interval: 5s
      timeout: 2s
      retries: 20
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile # same as of your docker file name
      args:
        DATABASE_URL: $DATABASE_URL
        DIRECT_URL: $DIRECT_URL
    environment:
      ENV_NAME: value # your environtment varibles value
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres-for-hourly
      DIRECT_URL: postgresql://postgres:password@db:5432/postgres-for-hourly
      DB_PORT: 5432
      JWT_SECRET: awicdbcZ6@6l
      EMAIL_HOST: sandbox.smtp.mailtrap.io
      EMAIL: 0cac8cdb07e99d
      EMAIL_PASSWORD: 18d59fa62a7e29
      DEBUG: roster:*
      NODE_ENV: local
      JHU_SSO_URL: https://idp.jh.edu/idp/profile/SAML2/Redirect/SSO
      SP_NAME: glacial-plateau-47269
      BASE_URL: https://glacial-plateau-47269.herokuapp.com
      CERT: ""
      PBK: "YOUR PUBLIC KEY"
      PVK: "YOUR PRIVATE KEY"
      HOURLY_API_KEY: api-key
      test: false
      DISABLE_EMAIL_SENDING: true
      FRONTEND_BASE_URL: localhost:3000
    volumes:
      - ./directory-path:/direcotory-end-name
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile # same as of your docker file name
      args:
        VITE_RUN_MODE: local
        VITE_LOC_BASE_URL: http://localhost:5000
        VITE_DEV_BASE_URL: https://proj-hourly-dev.herokuapp.com
        VITE_PROD_BASE_URL: https://proj-hourly-prod.herokuapp.com
        VITE_ROSTER_SSO_JHU_URL: https://glacial-plateau-47269.herokuapp.com/jhu/login
        VITE_USER_USERNAME: user-1
        VITE_USER_PASSWORD: user-1
        VITE_ADMIN_USERNAME: admin-1
        VITE_ADMIN_PASSWORD: admin-1
    environment:
      VITE_RUN_MODE: local
      VITE_LOC_BASE_URL: http://localhost:5000
      VITE_DEV_BASE_URL: https://proj-hourly-dev.herokuapp.com
      VITE_PROD_BASE_URL: https://proj-hourly-prod.herokuapp.com
      VITE_ROSTER_SSO_JHU_URL: https://glacial-plateau-47269.herokuapp.com/jhu/login
      VITE_USER_USERNAME: user-1
      VITE_USER_PASSWORD: user-1
      VITE_ADMIN_USERNAME: admin-1
      VITE_ADMIN_PASSWORD: admin-1
    volumes:
      - ./directory-path:/direcotory-end-name
    ports:
      - 3000:3000
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    image: proj-hourly-nginx
