version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-for-hourly
    ports:
      - "${DB_PORT}:5432" # HOST_PORT:CONTAINER_PORT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=$DATABASE_URL
        - DIRECT_URL=$DIRECT_URL
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres-for-hourly
      DIRECT_URL: postgresql://postgres:password@db:5432/postgres-for-hourly
      DB_PORT: 5432
      JWT_SECRET: awicdbcZ6@6l
      EMAIL_HOST: sandbox.smtp.mailtrap.io
      EMAIL: 0cac8cdb07e99d
      EMAIL_PASSWORD: 18d59fa62a7e29
      DEBUG: roster:*
      NODE_ENV: local
      JHU_SSO_URL: https://idp.jh.edu/idp/profile/SAML2/Redirect/SSO
      SP_NAME: glacial-plateau-47269
      BASE_URL: https://glacial-plateau-47269.herokuapp.com
      CERT: ""
      PBK: "YOUR PUBLIC KEY"
      PVK: "YOUR PRIVATE KEY"
      HOURLY_API_KEY: api-key
      test: false
      DISABLE_EMAIL_SENDING: true
      FRONTEND_BASE_URL: localhost:3000
    image: proj-hourly-server
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile # same as of your docker file name
      args:
        VITE_RUN_MODE: local
        VITE_LOC_BASE_URL: http://localhost:5000
        VITE_DEV_BASE_URL: https://proj-hourly-dev.herokuapp.com
        VITE_PROD_BASE_URL: https://proj-hourly-prod.herokuapp.com
        VITE_ROSTER_SSO_JHU_URL: https://glacial-plateau-47269.herokuapp.com/jhu/login
        VITE_USER_USERNAME: user-1
        VITE_USER_PASSWORD: user-1
        VITE_ADMIN_USERNAME: admin-1
        VITE_ADMIN_PASSWORD: admin-1
    environment:
      VITE_RUN_MODE: local
      VITE_LOC_BASE_URL: http://localhost:5000
      VITE_DEV_BASE_URL: https://proj-hourly-dev.herokuapp.com
      VITE_PROD_BASE_URL: https://proj-hourly-prod.herokuapp.com
      VITE_ROSTER_SSO_JHU_URL: https://glacial-plateau-47269.herokuapp.com/jhu/login
      VITE_USER_USERNAME: user-1
      VITE_USER_PASSWORD: user-1
      VITE_ADMIN_USERNAME: admin-1
      VITE_ADMIN_PASSWORD: admin-1
    volumes:
      - ./directory-path:/direcotory-end-name
    ports:
      - 3000:3000
    restart: always
