version: "3.9"
services:
  # In Docker
  # - DATABASE_URL=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - DATABASE_URL=postgres://prisma:prisma@localhost:5432/

  db:
    image: postgres:13
    restart: always
    container_name: postgres-with-prisma
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
