name: Build and Push Hourly Container

on:
  push:
    branches:
      - ChrisWilhelm_readme_update

env:
  DB_PORT: 5432
  DATABASE_URL: postgresql://postgres:password@127.0.0.1:5432/postgres-for-hourly
  DIRECT_URL: postgresql://postgres:password@127.0.0.1:5432/postgres-for-hourly
  DB_IMAGE_NAME: proj-hourly-db
  SERVER_IMAGE_NAME: proj-hourly-server
  FRONTEND_IMAGE_NAME: proj-hourly-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Get Docker image IDs
        run: |
          server_image_id=$(docker images -q ghcr.io/${{ github.repository }}-server:latest)
          frontend_image_id=$(docker images -q ghcr.io/${{ github.repository }}-client:latest)
          db_image_id=$(docker images -q ghcr.io/${{ github.repository }}-db:latest)

      - name: Tag and Push Docker images
        run: |
          docker tag $server_image_id ghcr.io/${{ github.repository }}-server:latest
          docker tag $frontend_image_id ghcr.io/${{ github.repository }}-client:latest
          docker tag $db_image_id ghcr.io/${{ github.repository }}-db:latest

          docker push ghcr.io/${{ github.repository }}-server:latest
          docker push ghcr.io/${{ github.repository }}-client:latest
          docker push ghcr.io/${{ github.repository }}-db:latest
