name: Build and Push Hourly Container

on:
  push:
    branches:
      - ChrisWilhelm_readme_update

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Tag and Push Docker images
        run: |
          docker-compose -f docker-compose.yml push
          docker tag server_image_id ghcr.io/${{ github.repository_owner }}/proj-hourly-server:latest
          docker tag frontend_image_id ghcr.io/${{ github.repository_owner }}/proj-hourly-frontend:latest
          docker tag db_image_id ghcr.io/${{ github.repository_owner }}/proj-hourly-db:latest
          docker push ghcr.io/${{ github.repository_owner }}/proj-hourly-server:latest
          docker push ghcr.io/${{ github.repository_owner }}/proj-hourly-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/proj-hourly-db:latest
