name: Build and Push Hourly Container

on:
  push:
    branches:
      - ChrisWilhelm_readme_update

env:
  DB_PORT: 5432
  DATABASE_URL: postgresql://postgres:password@127.0.0.1:5432/postgres-for-hourly
  DIRECT_URL: postgresql://postgres:password@127.0.0.1:5432/postgres-for-hourly
  DB_IMAGE_NAME: proj-hourly-db
  SERVER_IMAGE_NAME: proj-hourly-server
  FRONTEND_IMAGE_NAME: proj-hourly-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Get Docker image IDs
        id: get_image_ids
        run: |
          server_image_id=$(docker images -q $SERVER_IMAGE_NAME)
          frontend_image_id=$(docker images -q $FRONTEND_IMAGE_NAME)
          db_image_id=$(docker images -q $DB_IMAGE_NAME)
          echo "Server Image ID: $server_image_id"
          echo "Frontend Image ID: $frontend_image_id"
          echo "DB Image ID: $db_image_id"
          echo "::set-output name=server_image_id::$server_image_id"
          echo "::set-output name=frontend_image_id::$frontend_image_id"
          echo "::set-output name=db_image_id::$db_image_id"

      - name: Tag Docker images
        run: |
          docker tag ${{ steps.get_image_ids.outputs.server_image_id }} ghcr.io/${{ github.repository }}-server:latest
          docker tag ${{ steps.get_image_ids.outputs.frontend_image_id }} ghcr.io/${{ github.repository }}-client:latest
          docker tag ${{ steps.get_image_ids.outputs.db_image_id }} ghcr.io/${{ github.repository }}-db:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository }}-server:latest
          docker push ghcr.io/${{ github.repository }}-client:latest
          docker push ghcr.io/${{ github.repository }}-db:latest
