name: (prod) Deploy the client (frontend) app

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/prod.client.yml"

env:
  VITE_RUN_MODE: prod
  VITE_DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
  VITE_PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
  VITE_ROSTER_SSO_JHU_URL: ${{ secrets.ROSTER_SSO_JHU_URL }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          docker build --build-arg VITE_RUN_MODE=$VITE_RUN_MODE --build-arg VITE_DEV_BASE_URL=$VITE_DEV_BASE_URL --build-arg VITE_PROD_BASE_URL=$VITE_PROD_BASE_URL --build-arg VITE_ROSTER_SSO_JHU_URL=$VITE_ROSTER_SSO_JHU_URL --tag ghcr.io/${{ github.repository }}-ui:latest ./client
          docker push ghcr.io/${{ github.repository }}-ui:latest
      
      - name: Deploy to Caprover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.PROD_UI_APP_NAME }}
          token: ${{ secrets.PROD_UI_APP_TOKEN }}
          image: ghcr.io/${{ github.repository }}-ui:latest