name: (prod) Deploy the server (backend) app

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/prod.server.yml"

env:
  DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          docker build --build-arg DATABASE_URL=$DATABASE_URL --build-arg TARGET=production ./server --tag ghcr.io/${{ github.repository }}-api:latest
          docker push ghcr.io/${{ github.repository }}-api:latest
      
      - name: Deploy to Caprover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.PROD_API_APP_NAME }}
          token: ${{ secrets.PROD_API_APP_TOKEN }}
          image: ghcr.io/${{ github.repository }}-api:latest